//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int deal_id { get; set; }
        public int product_id { get; set; }
        public System.DateTime date_deal { get; set; }
        public decimal price { get; set; }
        public Nullable<int> card_id { get; set; }
        public int admin_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual DiscountCard DiscountCard { get; set; }
        public virtual Product Product { get; set; }
    }
}
